export const antiquesData = [
    {
        id: '1',
        collectionDate: '1990-05-11',
        price: 'EGP 30,000',
        productName: 'Flower Poetry',
        type: 'Antique Furniture',
        sellerName: 'Shafeek',
        description: 'Vintage wooden chair with floral carvings.',
        status: 'Vintage',
    },
    {
        id: '2',
        collectionDate: '1985-07-23',
        price: 'EGP 50,000',
        productName: 'Ancient Vase',
        type: 'Camera',
        sellerName: 'Ahmed',
        description: 'A beautifully painted vase from ancient Egypt.',
        status: 'Rare',
    },
    {
        id: '3',
        collectionDate: '1978-02-17',
        price: 'EGP 20,000',
        productName: 'Old Clock',
        type: 'Jewelry',
        sellerName: 'Fatima',
        description: 'A classic grandfather clock in perfect condition.',
        status: 'Vintage',
    },
    {
        id: '4',
        collectionDate: '1965-11-05',
        price: 'EGP 15,000',
        productName: 'Silver Cutlery Set',
        type: 'Jewelry',
        sellerName: 'Youssef',
        description: 'A complete set of silver cutlery from the 1960s.',
        status: 'Good',
    },
    {
        id: '5',
        collectionDate: '1995-09-30',
        price: 'EGP 25,000',
        productName: 'Painting of the Nile',
        type: 'Coins',
        sellerName: 'Layla',
        description: 'A beautiful painting depicting the Nile River.',
        status: 'Excellent',
    },
    {
        id: '6',
        collectionDate: '1980-12-12',
        price: 'EGP 40,000',
        productName: 'Antique Lamp',
        type: 'Jewelry',
        sellerName: 'Mohamed',
        description: 'An antique brass lamp with intricate designs.',
        status: 'Vintage',
    },
    {
        id: '7',
        collectionDate: '1975-06-20',
        price: 'EGP 60,000',
        productName: 'Old Radio',
        type: 'Batteries',
        sellerName: 'Khaled',
        description: 'A classic radio from the 1970s in working condition.',
        status: 'Vintage',
    },
    {
        id: '8',
        collectionDate: '1992-11-15',
        price: 'EGP 22,000',
        productName: 'Persian Rug',
        type: 'Coins',
        sellerName: 'Nour',
        description: 'A handmade Persian rug with beautiful patterns.',
        status: 'Excellent',
    },
    {
        id: '9',
        collectionDate: '1960-04-05',
        price: 'EGP 35,000',
        productName: 'Vintage Camera',
        type: 'Coins',
        sellerName: 'Sara',
        description: 'A vintage camera with original lens and case.',
        status: 'Good',
    },
    {
        id: '10',
        collectionDate: '1988-08-08',
        price: 'EGP 45,000',
        productName: 'Bronze Sculpture',
        type: 'Coins',
        sellerName: 'Hassan',
        description: 'A bronze sculpture depicting a historical figure.',
        status: 'Rare',
    },
    {
        id: '11',
        collectionDate: '1973-01-19',
        price: 'EGP 28,000',
        productName: 'Ancient Coin',
        type: 'Jewelry',
        sellerName: 'Omar',
        description: 'A rare coin from the Roman Empire era.',
        status: 'Rare',
    },
    {
        id: '12',
        collectionDate: '1967-03-14',
        price: 'EGP 33,000',
        productName: 'Vintage Book',
        type: 'Jewelry',
        sellerName: 'Aisha',
        description: 'A first edition of a classic novel.',
        status: 'Vintage',
    },
    {
        id: '13',
        collectionDate: '1999-05-25',
        price: 'EGP 27,000',
        productName: 'Old Map',
        type: 'Antique Furniture',
        sellerName: 'Huda',
        description: 'An old map showing the world as it was known in the 18th century.',
        status: 'Good',
    },
    {
        id: '14',
        collectionDate: '1982-11-30',
        price: 'EGP 37,000',
        productName: 'Classic Piano',
        type: 'Antique Furniture',
        sellerName: 'Samir',
        description: 'A classic piano from the 19th century.',
        status: 'Vintage',
    },
    {
        id: '15',
        collectionDate: '1971-09-02',
        price: 'EGP 55,000',
        productName: 'Antique Globe',
        type: 'Metal',
        sellerName: 'Karim',
        description: 'An antique globe with detailed geographical features.',
        status: 'Rare',
    } ,
    {
        id: '15',
        collectionDate: '1971-09-02',
        price: 'EGP 55,000',
        productName: 'Antique Globe',
        type: 'Metal',
        sellerName: 'Karim',
        description: 'An antique globe with detailed geographical features.',
        status: 'Rare',
    } ,

    {
        id: '2',
        collectionDate: '1985-07-23',
        price: 'EGP 50,000',
        productName: 'Ancient Vase',
        type: 'Metal',
        sellerName: 'Ahmed',
        description: 'A beautifully painted vase from ancient Egypt.',
        status: 'Rare',
    },
    {
        id: '3',
        collectionDate: '1978-02-17',
        price: 'EGP 20,000',
        productName: 'Old Clock',
        type: 'Ancient Manuscript',
        sellerName: 'Fatima',
        description: 'A classic grandfather clock in perfect condition.',
        status: 'Vintage',
    },
    {
        id: '4',
        collectionDate: '1965-11-05',
        price: 'EGP 15,000',
        productName: 'Silver Cutlery Set',
        type: 'Batteries',
        sellerName: 'Youssef',
        description: 'A complete set of silver cutlery from the 1960s.',
        status: 'Good',
    },
    {
        id: '5',
        collectionDate: '1995-09-30',
        price: 'EGP 25,000',
        productName: 'Painting of the Nile',
        type: 'Batteries',
        sellerName: 'Layla',
        description: 'A beautiful painting depicting the Nile River.',
        status: 'Excellent',
    },
];

// Musical Instruments  Decorative Items'